server:
  port: 8080
  shutdown: graceful
  error:
    whitelabel:
      enabled: true
  servlet:
    context-path: /api
spring:
  application:
    name: Lecture
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL  # 메모리 DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true          # 웹 콘솔 활성화
  jpa:
    hibernate:
      ddl-auto: create       # 테이블 자동 생성
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger/index.html
    supported-submit-methods: [get, post, put, delete]
    tags-sorter: alpha
    operations-sorter: method
    groups-order: ASC
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace